# scripts/pva/collect-evidence.ps1
#
# PR2.1 — Immutable evidence package for the EFD ICMS/IPI generated by the app
# (Generation 1, status pva_pending). Records cryptographic + structural metadata
# so the PVA validation result can be audited end-to-end.
#
# Run: pwsh scripts/pva/collect-evidence.ps1
#      (or: powershell -ExecutionPolicy Bypass -File scripts/pva/collect-evidence.ps1)

$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$SRC = Join-Path $RepoRoot "private-exports\probe-efd-fix\efd.txt"
$OUT = Join-Path $RepoRoot "docs\pva\2026-06\generation-1"
New-Item -ItemType Directory -Force -Path $OUT | Out-Null

if (-not (Test-Path $SRC)) {
  Write-Error "Source EFD not found: $SRC"
  exit 1
}

$GenId = "gen-1-2026-06"
$DestName = "efd-generated-1.txt"
$Dest = Join-Path $OUT $DestName
Copy-Item -LiteralPath $SRC -Destination $Dest -Force

# --- structural analysis ---
$bytes = [System.IO.File]::ReadAllBytes($Dest)
$size = $bytes.Length

# BOM detection
$bom = $null
if ($size -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) { $bom = "UTF-8 BOM" }
elseif ($size -ge 2 -and $bytes[0] -eq 0xFF -and $bytes[1] -eq 0xFE) { $bom = "UTF-16 LE BOM" }
elseif ($size -ge 2 -and $bytes[0] -eq 0xFE -and $bytes[1] -eq 0xFF) { $bom = "UTF-16 BE BOM" }
else { $bom = "none" }

# EOL detection (prefer counting CRLF vs bare LF)
$text = [System.IO.File]::ReadAllText($Dest)
$crlf = ([regex]::Matches($text, "`r`n")).Count
$lfOnly = ([regex]::Matches($text, "(?<=`r)`n|(?<!`r)`n")).Count
$eol = if ($crlf -gt 0) { "CRLF" } elseif ($lfOnly -gt 0) { "LF" } else { "none" }

$lines = $text.Split(@("`r`n", "`n"), [StringSplitOptions]::None).Count
$nfe = ([regex]::Matches($text, "\|(\d{3,4})\|")).Count  # rough EFD register count

# SHA-256 (file + content without BOM ambiguity: hash the raw bytes)
$sha = (Get-FileHash -LiteralPath $Dest -Algorithm SHA256).Hash
$srcSha = (Get-FileHash -LiteralPath $SRC -Algorithm SHA256).Hash

$manifest = [ordered]@{
  generationId      = $GenId
  obligation        = "efd-icms-ipi"
  period            = "2026-06"
  profile           = "A"
  layout            = "EFD ICMS/IPI (Guia Pratico 3.2.2)"
  status            = "pva_pending"
  generatedAtUtc    = ((Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ"))
  source            = @{
    path     = "private-exports/probe-efd-fix/efd.txt"
    sha256   = $srcSha
  }
  artifact          = @{
    fileName = $DestName
    sha256   = $sha
    byteSize = $size
    bom      = $bom
    eol      = $eol
    lineCount = $lines
    registryRecordCount = $nfe
    encoding = "detected from BOM / content"
  }
  pva               = @{
    tool          = "SpedEFD.exe (Programa da RFB)"
    expectedRun   = "Importar arquivo -> Validar -> coletar erros bloqueantes"
    resultStatus  = "pending_extraction"
    errors        = @()
    warnings      = @()
    aboutVersion  = $null
  }
  notes             = "Evidencia imutavel da Geracao 1. O arquivo efd-generated-1.txt e a copia " +
                      "byte-a-byte do fonte; o SHA-256 fixa a integridade para auditoria do ciclo PVA."
}

$manifestPath = Join-Path $OUT "manifest.json"
$manifest | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $manifestPath -Encoding utf8

# SHA256SUMS.txt (soma estilo sha256sum)
@(
  "$sha  $DestName"
  "$srcSha  ../probe-efd-fix/efd.txt (source)"
) | Set-Content -LiteralPath (Join-Path $OUT "SHA256SUMS.txt") -Encoding utf8

$readme = @"
# PVA Evidence — EFD ICMS/IPI — Geração 1 (2026-06, Perfil A)

Pacote de evidência imutável da Geração 1 do arquivo EFD ICMS/IPI gerado pelo app.

- **Arquivo:** \`$DestName\` (cópia byte-a-byte de \`private-exports/probe-efd-fix/efd.txt\`)
- **SHA-256:** \`$sha\`
- **Tamanho:** $size bytes · **BOM:** $bom · **EOL:** $eol · **Linhas:** $lines
- **Registros (aprox.):** $nfe
- **Status:** \`pva_pending\` — aguardando validação no PVA oficial (SpedEFD.exe)

## Próximo passo
Importar \`$DestName\` no SpedEFD.exe, rodar a validação e registrar os erros
bloqueantes em \`manifest.json > pva.errors\` (via \`scripts/pva/parse-pva-report.ps1\`
ou import manual). O \`aboutVersion\` deve ser preenchido com a versão real do PVA
(launcher reporta 2.1.1-SNAPSHOT; a versão do aplicativo PVA é outra — ver tela "Sobre").
"@
Set-Content -LiteralPath (Join-Path $OUT "README.md") -Encoding utf8 -Value $readme

Write-Host "[collect-evidence] wrote package to $OUT"
Write-Host "[collect-evidence] SHA-256: $sha"
Write-Host "[collect-evidence] size=$size BOM=$bom EOL=$eol lines=$lines records~$nfe"
